// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomBooking.Infrastructure.Persistence;

#nullable disable

namespace RoomBooking.Infrastructure.Migrations
{
    [DbContext(typeof(RoomBookingDbContext))]
    partial class RoomBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomBooking.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Organizador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QntdPessoas")
                        .HasColumnType("int");

                    b.Property<Guid>("SalaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("RoomBooking.Domain.Entities.Sala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Salas", (string)null);
                });

            modelBuilder.Entity("RoomBooking.Domain.Entities.Reserva", b =>
                {
                    b.OwnsOne("RoomBooking.Domain.ValueObjects.Periodo", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Fim")
                                .HasColumnType("datetime2")
                                .HasColumnName("Fim");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("Inicio");

                            b1.HasKey("ReservaId");

                            b1.ToTable("Reservas");

                            b1.WithOwner()
                                .HasForeignKey("ReservaId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("RoomBooking.Domain.Entities.Sala", b =>
                {
                    b.OwnsOne("RoomBooking.Domain.ValueObjects.Capacidade", "Capacidade", b1 =>
                        {
                            b1.Property<Guid>("SalaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("int")
                                .HasColumnName("Capacidade");

                            b1.HasKey("SalaId");

                            b1.ToTable("Salas");

                            b1.WithOwner()
                                .HasForeignKey("SalaId");
                        });

                    b.Navigation("Capacidade")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
